# Descrição do dataset

Dados do SUS sobre a incidência de de dengue no Brasil

In [1]:
import numpy as np
import pandas as pd

In [2]:
data = pd.read_csv('data/dengue_2000_dataset.csv', sep = ',')
#data.head(5)
data = data.dropna(axis = 1, how = 'all')
data.to_csv('data/no_missing_columns.csv', sep=',')

/usr/local/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2785: DtypeWarning: Columns (15,27,29,31,43,51,64,66,67,70,71,73,74,75,78,79,80,97,107) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


Número de instâncias

In [3]:
data.shape[0]

172855

Número de características

In [4]:
data.shape[1] - 1

108

Número de instâncias sem valores faltantes (missing values)

In [5]:
no_missing = data.dropna()
no_missing.shape[0]

0

Diferentes classificações no dataset

In [6]:
data['CON_CLASSI'].unique()

array([ 1.,  5., nan,  0.,  3.,  2.,  8.,  4.])

In [7]:
data['DENGUE'].unique()

array([ 2., nan,  9.,  1.])

In [8]:
data['FEBRE'].unique()

array([ 1., nan,  2.,  9.])

In [9]:
data['VACINADO'].unique()

array([nan,  1.,  2.,  9.])

In [10]:
#data.isnull().head(5)
series = data.isnull().sum()

In [11]:
column_names = []
for k, v in series.items():
    if (data.shape[0] - v) / data.shape[0] < 0.7:
        print(v)
        column_names.append(k)
        
print(len(column_names)) 
print(column_names)

167795
71526
99954
172469
164387
78926
172764
170636
170596
89553
168846
168934
172838
52658
52934
168101
168108
168107
53142
172853
54353
55240
168182
54161
168142
168115
52570
168129
168121
169078
172853
168642
172833
172823
172823
169218
169388
172098
172128
121935
172021
171706
172846
125614
168487
168965
169656
172850
172852
164815
172790
172818
172820
171304
167661
167679
172849
172850
172519
172853
172518
98997
96809
154953
158131
172850
142330
160683
68
['CS_RACA', 'ID_BAIRRO', 'ID_DT_RESI', 'OCUPACAO', 'ANO', 'VACINADO', 'DT_DOSE', 'DT_FEBRE', 'DURACAO', 'LACO', 'DIARREIA', 'OUTROS', 'SIN_OUT', 'EPISTAXE', 'GENGIVO', 'METRO', 'HEMATURA', 'SANGRAM', 'OUTROS_M', 'OUTROS_M_D', 'ASCITE', 'PLEURAL', 'PERICARDI', 'HEPATO', 'MIOCARDI', 'HIPOTENSAO', 'CHOQUE', 'MANIFESTA', 'INSUFICIEN', 'OUTRO_S', 'DT_CHOQUE', 'HOSPITALIZ', 'DT_INTERNA', 'UF', 'MUNICIPIO', 'DT_COL_HEM', 'DT_COL_PLQ', 'DT_COL_HE2', 'DT_COL_PL2', 'DT_SORO1', 'DT_SORO2', 'DT_SOROR1', 'DT_SOROR2', 'S1_IGM', 'S1_IGG', 'S2_

In [12]:
for c in column_names:
    del data[c]
    
print(data.shape)

(172855, 41)


In [13]:
only_eights = data[data['CON_CLASSI'] == 8]

In [15]:
only_eights.shape[0]

455